spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: myspringcloudconfig-dev

---
spring:
  profiles: test
  application:
    name: myspringcloudconfig-test

---
spring:
  profiles: prod
  application:
    name: myspringcloudconfig-prod
