spring:
  application:
    name: eureka-provider01
  profiles:
    include: model
githubpass: '{cipher}AgAtrQPXVTjvhYDnmgCzqFzAhhAM9hMGjD0YgYQk+KZivKsfZVSvQ4xRTDf2a34stDjoh/j2mJQLFJ5v3Ype232x8z2PE7Aqt/EkxQLSoqMQec4095WI+Z9Kw2rTK9D9FMFenvHUWtcv5k13+Ew6pXDPRFsZlYQHd5otgM+dp+Fqm2AZh9gBDevZ8qvBA18A9UiodjIjWrf+EckHiGzZmlxqchEfykcAHqV2tgWzSCAZDUCEAnSEVSXgVvdEdGFW1Ne6h/vAjIZwMKH9eAdqajBFSKF81nFhvXk+xqphxW3Hc97PphC9e325Softf5GhO1WTJGDB+X3ZKgRzJ8G4gIhZyrK9lUcEvRhoB91TZXzFZHLG9mHbmVsz/qLWhmLprIvOo1FPQCqpaoEQCnSYtWDNSfV8+yMompEs9b1zMIneQ2AC8uKgkhRxnX3jF7p9RVl7wXq1502ol8ObdAqux48WsnMDQk4U/IK4A/XVcG315CWQK3XfubKVwa9FaZUcLJ+dmH3uboIlmCx8KfLYWChicudI1l0NAxxgTrcV92i578OhzulPv7QpAUbrfpdW9HDo0yQqiMN6GSMxIKPt04bfylRDg/cmNi9GYUhpDycoWzt3AckarATwVnd0VLYJMhPbWuLybrNREO+WXQ0pg+XQyDtGIsMmlxQZF2lD8VBUMdEabeMf+uV7wb42cMHrdIA4gLYhmvz1OWXvR0e9ube9'
#eureka:
#  instance:
#    appname: myeurekaprovider
#    hostname: localhost
#    instance-id: ${eureka.instance.appname}:${server.port}
#  client:
#    service-url:
#      defaultZone: http://eureka8853.com:8853/eureka/,http://eureka8854.com:8854/eureka/,http://eureka8854.com:8849/eureka/
