spring:
  application:
    name: eureka-provider01
  profiles:
    include: model
githubpass: '{cipher}31d2344f26a2f2612065f6f8481a846ce0f1a4ad1f0121d46a609009c40640b8'
#eureka:
#  instance:
#    appname: myeurekaprovider
#    hostname: localhost
#    instance-id: ${eureka.instance.appname}:${server.port}
#  client:
#    service-url:
#      defaultZone: http://eureka8853.com:8853/eureka/,http://eureka8854.com:8854/eureka/,http://eureka8854.com:8849/eureka/
